services:
  redis:
    image: redis:8.6-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  kubecrab:
    image: kubecrab
    build:
      context: .
    environment:
      - SECRET_KEY_BASE
      - RAILS_SSL
    volumes:
      - kubecrab-data:/rails/storage
    ports:
      - 3000:3000
  kubecrab-worker:
    image: kubecrab
    command: bin/jobs
    build:
      context: .
    environment:
      - SECRET_KEY_BASE
      - RAILS_SSL
    volumes:
      - kubecrab-data:/rails/storage

volumes:
  redis-data:
  kubecrab-data:
